trainers:
  - name: Babelle Lyrn
    message: You feel closer to understanding the Sylvan language.
    class: Common
    subclass: Language
  - name: Bruia Stout
    message: You feel more skilled in the art of brewing.
    class: Common
    subclass: Crafting
  - name: Master Bodrus
    message: Your body feels stronger.
    class: Common
  - name: Skea Brightfur
    message: Your study of skinning seems to be paying off.
  - name: Awaria
    message: You seem to heal yourself more easily with the moonstone.
  - name: Eva
    message: You seem to heal more effectively.
  - name: Faustus
    message: You notice yourself healing others faster.
  - name: Higgrus
    message: ""
  - name: Horus
    message: You seem to heal people closer to death now.
  - name: Proximus
    message: You seem to heal from further away now.
  - name: Respia
    message: You seem to recover spiritual energy faster.
  - name: Sespus
    message: You notice that you can use your healing ability longer.
  - name: Sprite
    message: Your healing spirit improves.
  - name: Sylpha
    message: You understand the walking self-heal technique better.
  - name: Atkus
    message: You seem to attack more precisely now.
  - name: Balthus
    message: ""
  - name: Darkus
    message: ""
  - name: Detha
    message: You seem to be defending yourself better.
  - name: Evus
    message: You seem to fight more effectively now.
  - name: Histia
    message: ""
  - name: Regia
    message: You notice your balance recovering more quickly.
  - name: Swengus
    message: You notice your balance and recovery improving.
  - name: Poly Carver
    message: You feel more skilled in the craft of woodworking.
  - name: Forgus
    message: Your knowledge of blacksmithing improves.
progressmessages:
  - message: It is good to see you.
    ranks: 10
  - message: Your persistence is paying off.
    ranks: 20
  - message: You are progressing well.
    ranks: 30
  - message: You are a good pupil of mine.
    ranks: 40
  - message: You are one of my better pupils.
    ranks: 50
  - message: You keep me on my toes.
    ranks: 100
  - message: It is hard to find more to teach you.
    ranks: 150
  - message: Teaching you is a challenge.
    ranks: 200
  - message: There is not much more I can teach you.
    ranks: 250
  - message: Teaching you has taught me much.
    ranks: 300
  - message: You have attained tremendous skill.
    ranks: 350
  - message: We are nearly equals.
    ranks: 400
  - message: You may be proud of your accomplishment.
    ranks: 450
  - message: You are becoming a master of our art.
    ranks: 500
