trainers:
  - name: Babelle Lyrn
    message: You feel closer to understanding the Sylvan language.
    class: Common
    subclass: Language
  - name: Bruia Stout
    message: You feel more skilled in the art of brewing.
    class: Common
    subclass: Crafting
  - name: Master Bodrus
    message: Your body feels stronger.
    class: Common
    isCombinationTrainer: yes
  - name: Skea Brightfur
    message: Your study of skinning seems to be paying off.
    class: Common
    subclass: Bounty

  - name: Awaria
    message: You seem to heal yourself more easily with the moonstone.
    class: Healer
  - name: Eva
    message: You seem to heal more effectively.
    class: Healer
    isCombinationTrainer: yes
  - name: Faustus
    message: You notice yourself healing others faster.
    class: Healer
  - name: Higgrus
    message: You seem to be able to take more damage now.
    class: Healer
  - name: Horus
    message: You seem to heal people closer to death now.
    class: Healer
  - name: Proximus
    message: You seem to heal from further away now.
    class: Healer
  - name: Respia
    message: You seem to recover spiritual energy faster.
    class: Healer
  - name: Sespus
    message: You notice that you can use your healing ability longer.
    class: Healer
  - name: Sprite
    message: Your healing spirit improves.
    class: Healer
    isCombinationTrainer: yes
  - name: Sylpha
    message: You understand the walking self-heal technique better.
    class: Healer

  - name: Atkus
    message: You seem to attack more precisely now.
    class: Fighter
  - name: Balthus
    message: ""
    class: Fighter
  - name: Darkus
    message: ""
    class: Fighter
  - name: Detha
    message: You seem to be defending yourself better.
    class: Fighter
  - name: Evus
    message: You seem to fight more effectively now.
    class: Fighter
    isCombinationTrainer: yes
  - name: Histia
    message: You seem to be able to take more damage now.
    class: Fighter
  - name: Regia
    message: You notice your balance recovering more quickly.
    class: Fighter
  - name: Swengus
    message: You notice your balance and recovery improving.
    class: Fighter
    isCombinationTrainer: yes
  - name: Poly Carver
    message: You feel more skilled in the craft of woodworking.
    class: Common
    subclass: Crafting
  - name: Forgus
    message: Your knowledge of blacksmithing improves.
    class: Common
    subclass: Crafting

progressmessages:
  - message: It is good to see you.
    ranks: 10
  - message: Your persistence is paying off.
    ranks: 20
  - message: You are progressing well.
    ranks: 30
  - message: You are a good pupil of mine.
    ranks: 40
  - message: You are one of my better pupils.
    ranks: 50
  - message: You keep me on my toes.
    ranks: 100
  - message: It is hard to find more to teach you.
    ranks: 150
  - message: Teaching you is a challenge.
    ranks: 200
  - message: There is not much more I can teach you.
    ranks: 250
  - message: Teaching you has taught me much.
    ranks: 300
  - message: You have attained tremendous skill.
    ranks: 350
  - message: We are nearly equals.
    ranks: 400
  - message: You may be proud of your accomplishment.
    ranks: 450
  - message: You are becoming a master of our art.
    ranks: 500
  - message: Your dedication is commendable.
    ranks: 550
  - message: You show great devotion to your studies.
    ranks: 600
  - message: You are a credit to our craft.
    ranks: 650
  - message: Few indeed are your peers.
    ranks: 700
  - message: Your devotion to the craft is exemplary.
    ranks: 750
  - message: It is always good to greet a respected colleague.
    ranks: 800
  - message: You are truly a grand master.
    ranks: 900
  - message: Let us search for more we might learn together.
    ranks: 1000
  - message: Your persistence is an example to us all.
    ranks: 1250
  - message: Your skill astounds me.
    ranks: 1500
  - message: You have progressed further than most.
    ranks: 1750
  - message: You are nearly peerless.
    ranks: 2000
